FIX(SdlModule.cpp) changing the window size : frome 800x600 to 1920x1080

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,97 +1,115 @@
-name: chocolatine
-
-env:
-  MIRROR_URL: git@github.com:EpitechPGEPromo2029/B-DOP-200-LIL-2-1-chocolatine-thomas.villot.git
-  EXECUTABLE: ./anagram
-
 on:
-  push:
-    branches-ignore:
-      - "ga-ignore"
-  pull_request:
-    branches-ignore:
-      - "ga-ignore"
-  check_run:
-    types: [rerequested, completed]
+    push:
+      branches-ignore:
+        - ga-ignore-*
+    pull_request:
+      branches-ignore:
+        - ga-ignore-*
 
-jobs:
-  check_repository:
-    runs-on: ubuntu-latest
-    outputs:
-      should_continue: ${{ steps.check_repo.outputs.should_continue }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: Check if repository is the mirror
-        id: check_repo
-        run: |
-          if [[ "git@github.com:${{ github.repository }}.git" == "${{env.MIRROR_URL}}" ]]; then
-            echo "Already in Epitech repository, no need to continue"
-            echo "should_continue=false" >> "$GITHUB_OUTPUT"
-          else
-            echo "Running on fork, continue workflow"
-            echo "should_continue=true" >> "$GITHUB_OUTPUT"
-          fi
+  env:
+    MIRROR_REPO:
+    MIRROR_URL:
+    EXECUTABLES:
 
-  check_coding_style:
-    needs: check_repository
-    if: ${{ needs.check_repository.outputs.should_continue == 'true' }}
-    runs-on: ubuntu-latest
-    container:
-      image: ghcr.io/epitech/coding-style-checker:latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Run coding style checker
-        run: |
-          check.sh $(pwd) $(pwd)
-          if [ ! -s "coding-style-reports.log" ]; then
-            echo "Coding style OK"
-          else
-            echo "Coding style errors detected"
-            exit 1
-          fi
+  jobs:
+      check_repository:
+        runs-on: ubuntu-latest
+        steps:
+          - name: Check if the current repository is the same as the target one
+            run: |
+                if [[ "$GITHUB_REPOSITORY" == $MIRROR_REPO ]]; then
+                  exit 1
+                fi
 
-  check_program_compilation:
-    needs: check_coding_style
-    if: ${{ needs.check_repository.outputs.should_continue == 'true' }}
-    runs-on: ubuntu-latest
-    timeout-minutes: 2
-    container:
-      image: epitechcontent/epitest-docker
-    steps:
-      - uses: actions/checkout@v4
-      - name: Build project
-        run: |
-          make
-          if [ ! -f "${{ env.EXECUTABLE }}" ]; then
-            echo "Compilation failed: Executable not found"
-            exit 1
-          fi
-      - name: Clean project
-        run: make clean
+      check_coding_style:
+          runs-on: ubuntu-latest
+          needs: check_repository
+          container:
+            image: ghcr.io/epitech/coding-style-checker:latest
+          steps:
+              - name: Checkout repository
+                uses: actions/checkout@v4
+                with:
+                  fetch-depth: 0
 
-  run_tests:
-    needs: check_program_compilation
-    if: ${{ needs.check_repository.outputs.should_continue == 'true' }}
-    runs-on: ubuntu-latest
-    timeout-minutes: 2
-    container:
-      image: epitechcontent/epitest-docker
-    steps:
-      - uses: actions/checkout@v4
-      - name: Run tests
-        run: |
-          make tests_run
+              - name: Run coding style checker
+                run: check.sh $(pwd) $(pwd)
 
-  push_to_mirror:
-    needs: [check_repository, run_tests]
-    if: ${{ needs.check_repository.outputs.should_continue == 'true' && github.event_name == 'push' }}
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Mirror to target repository
-        uses: pixta-dev/repository-mirroring-action@v1
-        with:
-          target_repo_url: ${{ env.MIRROR_URL }}
-          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+              - name: Check if coding-style-reports.log exists
+                run: |
+                  if [ ! -f "coding-style-reports.log" ]; then
+                    exit 1
+                  fi
+
+              - name: Convert coding-style-reports.log in some git annotations
+                run: |
+                  if [ -s coding-style-reports.log ]; then
+                    grep ":" coding-style-reports.log | while IFS= read -r line; do
+                        FILE=$(echo "$line" | awk -F':' '{print $1}' | sed 's|./||')
+                        LINE=$(echo "$line" | awk -F':' '{print $2}')
+                        TYPE=$(echo "$line" | awk -F':' '{print $3}' | cut -d'-' -f1)
+                        CODE=$(echo "$line" | awk -F':' '{print $4}')
+                        echo "::error file=$FILE,line=$LINE,title=$TYPE coding style error::$CODE"
+                    done
+                    exit 1
+                  fi
+
+
+      check_program_compilation:
+          runs-on: ubuntu-latest
+          needs: check_coding_style
+          container:
+            image: epitechcontent/epitest-docker:latest
+          steps:
+              - name: Checkout repository
+                uses: actions/checkout@v4
+                with:
+                  fetch-depth: 0
+
+              - name: Run compilation
+                run: make timeout=120
+
+              - name: Clear repository
+                run: make clean
+
+              - name: Check if all executables are executable
+                run: |
+                    echo "$EXECUTABLES" | tr ',' '\n' | while read -r executable; do
+                      if [ ! -x "$executable" ]; then
+                        echo "Error: $executable is not executable or does not exist."
+                        exit 1
+                      fi
+                      echo "$executable ok"
+                    done
+
+
+      run_tests:
+          runs-on: ubuntu-latest
+          needs: check_program_compilation
+          container:
+            image: epitechcontent/epitest-docker:latest
+          steps:
+              - name: Checkout repository
+                uses: actions/checkout@v4
+                with:
+                  fetch-depth: 0
+
+              - name: Run tests in Docker
+                run: make tests_run timeout=120
+
+
+      push_to_mirror:
+          runs-on: ubuntu-latest
+          needs: run_tests
+          if: github.event_name == 'push'
+          steps:
+            - name: Checkout repository
+              uses: actions/checkout@v4
+              with:
+                fetch-depth: 0
+
+            - name: Clone repository
+              uses: pixta-dev/repository-mirroring-action@v1
+              with:
+                target_repo_url: ${{ env.MIRROR_URL }}
+                ssh_private_key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}
