FIX(SdlModule.cpp) changing the window size : frome 800x600 to 1920x1080

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,114 +1,87 @@
+name: Chocolatine Auto Checker
+
 on:
-    push:
-      branches-ignore:
-        - ga-ignore-*
-    pull_request:
-      branches-ignore:
-        - ga-ignore-*
-  env:
-    MIRROR_REPO:
-    MIRROR_URL:
-    EXECUTABLES:
+  push:
+    branches-ignore:
+      - 'ga-ignore-*'
+  pull_request:
+    branches-ignore:
+      - 'ga-ignore-*'
 
-  jobs:
-      check_repository:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Check if the current repository is the same as the target one
-            run: |
-                if [[ "$GITHUB_REPOSITORY" == $MIRROR_REPO ]]; then
-                  exit 1
-                fi
+env:
+  MIRROR_URL: ${{ secrets.MIRROR_URL }}
+  EXECUTABLES:
 
-      check_coding_style:
-          runs-on: ubuntu-latest
-          needs: check_repository
-          container:
-            image: ghcr.io/epitech/coding-style-checker:latest
-          steps:
-              - name: Checkout repository
-                uses: actions/checkout@v4
-                with:
-                  fetch-depth: 0
+jobs:
+  coding-style:
+    name: "Check Coding Style"
+    runs-on: ubuntu-latest
+    container: ghcr.io/epitech/coding-style-checker:latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
-              - name: Run coding style checker
-                run: check.sh $(pwd) $(pwd)
+      - name: Verify coding style
+        run: |
+          check.sh $(pwd) $(pwd)
+          [ ! -s coding-style-reports.log ] || {
+            while IFS=: read -r file line error; do
+              echo "::error file=$file,line=$line::$error"
+            done < coding-style-reports.log
+            exit 1
+          }
 
-              - name: Check if coding-style-reports.log exists
-                run: |
-                  if [ ! -f "coding-style-reports.log" ]; then
-                    exit 1
-                  fi
+  compilation:
+    name: "Check Compilation"
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker
+    needs: coding-style
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
 
-              - name: Convert coding-style-reports.log in some git annotations
-                run: |
-                  if [ -s coding-style-reports.log ]; then
-                    grep ":" coding-style-reports.log | while IFS= read -r line; do
-                        FILE=$(echo "$line" | awk -F':' '{print $1}' | sed 's|./||')
-                        LINE=$(echo "$line" | awk -F':' '{print $2}')
-                        TYPE=$(echo "$line" | awk -F':' '{print $3}' | cut -d'-' -f1)
-                        CODE=$(echo "$line" | awk -F':' '{print $4}')
-                        echo "::error file=$FILE,line=$LINE,title=$TYPE coding style error::$CODE"
-                    done
-                    exit 1
-                  fi
+      - name: Building project
+        run: make
+        timeout-minutes: 2
 
+      - name: Cleaning build files
+        run: make clean
 
-      check_program_compilation:
-          runs-on: ubuntu-latest
-          needs: check_coding_style
-          container:
-            image: epitechcontent/epitest-docker:latest
-          steps:
-              - name: Checkout repository
-                uses: actions/checkout@v4
-                with:
-                  fetch-depth: 0
+      - name: Validating executables presence
+        run: |
+          IFS=',' read -ra EXECS <<< "${EXECUTABLES}"
+          ERROR=0
+          for EXE in "${EXECS[@]}"; do
+            [ -x "$EXE" ] || {
+              echo "::error file=$EXE::Executable '$EXE' missing or not executable."
+              ERROR=1
+            }
+          done
+          exit $ERROR
 
-              - name: Run compilation
-                run: make timeout=120
+  tests-unit:
+    name: "Run Unit Tests"
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker
+    needs: compilation
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
 
-              - name: Clear repository
-                run: make clean
+      - name: Running tests suite
+        run: make tests_run
+        timeout-minutes: 2
 
-              - name: Check if all executables are executable
-                run: |
-                    echo "$EXECUTABLES" | tr ',' '\n' | while read -r executable; do
-                      if [ ! -x "$executable" ]; then
-                        echo "Error: $executable is not executable or does not exist."
-                        exit 1
-                      fi
-                      echo "$executable ok"
-                    done
-
-
-      run_tests:
-          runs-on: ubuntu-latest
-          needs: check_program_compilation
-          container:
-            image: epitechcontent/epitest-docker:latest
-          steps:
-              - name: Checkout repository
-                uses: actions/checkout@v4
-                with:
-                  fetch-depth: 0
-
-              - name: Run tests in Docker
-                run: make tests_run timeout=120
-
-
-      push_to_mirror:
-          runs-on: ubuntu-latest
-          needs: run_tests
-          if: github.event_name == 'push'
-          steps:
-            - name: Checkout repository
-              uses: actions/checkout@v4
-              with:
-                fetch-depth: 0
-
-            - name: Clone repository
-              uses: pixta-dev/repository-mirroring-action@v1
-              with:
-                target_repo_url: ${{ env.MIRROR_URL }}
-                ssh_private_key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}
+  repo-mirroring:
+    name: "Mirror Repository"
+    runs-on: ubuntu-latest
+    if: github.event_name == 'push' && github.repository != env.MIRROR_URL
+    needs: tests-unit
+    steps:
+      - name: Repository mirroring to Epitech
+        uses: pixta-dev/repository-mirroring-action@v1
+        with:
+          target_repo_url: ${{ env.MIRROR_URL }}
+          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
